# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- gimstage

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Copying_the_code_to_VM
    displayName: 'Copying-the-code'
    jobs:
      - job: CopyCode
        steps:
          - checkout: self
            displayName: 'copied code'
          
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'linux-vm'
              contents: '**/*'
              targetFolder: '/home/vmadmin/gim-app'
              cleanTargetFolder: True
              readyTimeout: '20000'

  - stage: Build_the_code
    displayName: 'Build-the-code'
    jobs:
      - job: BuildCode
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'linux-vm'
              runOptions: 'commands'
              commands: |
                cd /home/vmadmin/gim-app
                ls -la /home/vmadmin/gim-app
                ~/.local/bin/poetry lock
                ~/.local/bin/poetry install
                ~/.local/bin/poetry run serve
              

        
