# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Copying the code to VM
    displayName: 'Copying the code'
    jobs:
      - job: CopyCode
        steps:
          - checkout: self
            displayName: 'copied code'
          
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'linux-vm'
              contents: '**'
              targetFolder: '/home/vmadmin/gim-app'
              readyTimeout: '20000'

        
